subprojects {
	apply plugin: 'java'

	group = project.mod_group_id
	version = project.mod_version

	base {
		archivesName = "${project.mod_id}-${project.name}"
	}

	repositories {
		mavenCentral()
		maven { name = 'MinecraftForge'; url = 'https://maven.minecraftforge.net/' }
	}

	java {
		toolchain.languageVersion = JavaLanguageVersion.of(project.java_version as int)
		withSourcesJar()
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.encoding = 'UTF-8'
	}

	tasks.withType(ProcessResources).configureEach {
		var replacements = [
				mod_id         : project.mod_id,
				mod_name       : project.mod_name,
				mod_version    : project.mod_version,
				mod_authors    : project.mod_authors,
				mod_description: project.mod_description,
				mod_license    : project.mod_license,
				minecraft_version: project.minecraft_version,
				minecraft_version_min : project.minecraft_version_min,
				minecraft_version_next: project.minecraft_version_next,
		]
		it.inputs.properties replacements
		it.filesMatching(['META-INF/mods.toml']) {
			expand replacements
		}
	}
}
