pluginManagement {
	repositories {
		maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
		maven { name = 'NeoForged'; url = 'https://maven.neoforged.net/releases' }
		maven { name = 'MinecraftForge'; url = 'https://maven.minecraftforge.net/' }
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'TNTimer'

include 'common'
include 'fabric'
include 'neoforge'
include 'forge'
