modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Gabrieli2806/TNTimer/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
iconFile = "assets/tntimer/icon.png"
displayURL = "https://modrinth.com/mod/tntimer"

[[mixins]]
config = "tntimer.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},${minecraft_version_next})"
ordering = "NONE"
side = "CLIENT"
